module.exports = [ [ 'Cincinnati Bengals $$ Indianapolis Colts',
    'Tampa Bay Buccaneers $$ New Orleans Saints',
    'Tennessee Titans $$ Miami Dolphins',
    'Los Angeles Rams $$ Oakland Raiders',
    'Washington Redskins $$ Arizona Cardinals',
    'San Francisco 49ers $$ Minnesota Vikings',
    'Seattle Seahawks $$ Denver Broncos',
    'Jacksonville Jaguars $$ New York Giants',
    'Chicago Bears $$ Green Bay Packers',
    'New York Jets $$ Detroit Lions',
    'Kansas City Chiefs $$ Los Angeles Chargers',
    'Atlanta Falcons $$ Philadelphia Eagles',
    'Buffalo Bills $$ Baltimore Ravens',
    'Dallas Cowboys $$ Carolina Panthers',
    'Houston Texans $$ New England Patriots',
    'Pittsburgh Steelers $$ Cleveland Browns' ],
  [ 'New England Patriots $$ Jacksonville Jaguars',
    'Oakland Raiders $$ Denver Broncos',
    'Kansas City Chiefs $$ Pittsburgh Steelers',
    'Baltimore Ravens $$ Cincinnati Bengals',
    'New York Giants $$ Dallas Cowboys',
    'Indianapolis Colts $$ Washington Redskins',
    'Philadelphia Eagles $$ Tampa Bay Buccaneers',
    'Miami Dolphins $$ New York Jets',
    'Houston Texans $$ Tennessee Titans',
    'Los Angeles Chargers $$ Buffalo Bills',
    'Carolina Panthers $$ Atlanta Falcons',
    'Arizona Cardinals $$ Los Angeles Rams',
    'Minnesota Vikings $$ Green Bay Packers',
    'Cleveland Browns $$ New Orleans Saints',
    'Detroit Lions $$ San Francisco 49ers',
    'Seattle Seahawks $$ Chicago Bears' ],
  [ 'Cincinnati Bengals $$ Carolina Panthers',
    'New England Patriots $$ Detroit Lions',
    'New Orleans Saints $$ Atlanta Falcons',
    'Denver Broncos $$ Baltimore Ravens',
    'Tennessee Titans $$ Jacksonville Jaguars',
    'New York Jets $$ Cleveland Browns',
    'Los Angeles Chargers $$ Los Angeles Rams',
    'Buffalo Bills $$ Minnesota Vikings',
    'San Francisco 49ers $$ Kansas City Chiefs',
    'Chicago Bears $$ Arizona Cardinals',
    'Indianapolis Colts $$ Philadelphia Eagles',
    'Pittsburgh Steelers $$ Tampa Bay Buccaneers',
    'Dallas Cowboys $$ Seattle Seahawks',
    'Oakland Raiders $$ Miami Dolphins',
    'Green Bay Packers $$ Washington Redskins',
    'New York Giants $$ Houston Texans' ],
  [ 'Miami Dolphins $$ New England Patriots',
    'Detroit Lions $$ Dallas Cowboys',
    'Tampa Bay Buccaneers $$ Chicago Bears',
    'New Orleans Saints $$ New York Giants',
    'San Francisco 49ers $$ Los Angeles Chargers',
    'Cincinnati Bengals $$ Atlanta Falcons',
    'New York Jets $$ Jacksonville Jaguars',
    'Houston Texans $$ Indianapolis Colts',
    'Minnesota Vikings $$ Los Angeles Rams',
    'Buffalo Bills $$ Green Bay Packers',
    'Cleveland Browns $$ Oakland Raiders',
    'Philadelphia Eagles $$ Tennessee Titans',
    'Kansas City Chiefs $$ Denver Broncos',
    'Seattle Seahawks $$ Arizona Cardinals',
    'Baltimore Ravens $$ Pittsburgh Steelers' ],
  [ 'Jacksonville Jaguars $$ Kansas City Chiefs',
    'Dallas Cowboys $$ Houston Texans',
    'Baltimore Ravens $$ Cleveland Browns',
    'Green Bay Packers $$ Detroit Lions',
    'Washington Redskins $$ New Orleans Saints',
    'Miami Dolphins $$ Cincinnati Bengals',
    'Arizona Cardinals $$ San Francisco 49ers',
    'Los Angeles Rams $$ Seattle Seahawks',
    'Tennessee Titans $$ Buffalo Bills',
    'New York Giants $$ Carolina Panthers',
    'Minnesota Vikings $$ Philadelphia Eagles',
    'Denver Broncos $$ New York Jets',
    'Indianapolis Colts $$ New England Patriots',
    'Atlanta Falcons $$ Pittsburgh Steelers',
    'Oakland Raiders $$ Los Angeles Chargers' ],
  [ 'Kansas City Chiefs $$ New England Patriots',
    'Philadelphia Eagles $$ New York Giants',
    'Baltimore Ravens $$ Tennessee Titans',
    'Seattle Seahawks $$ Oakland Raiders',
    'Indianapolis Colts $$ New York Jets',
    'Los Angeles Chargers $$ Cleveland Browns',
    'Chicago Bears $$ Miami Dolphins',
    'Tampa Bay Buccaneers $$ Atlanta Falcons',
    'San Francisco 49ers $$ Green Bay Packers',
    'Los Angeles Rams $$ Denver Broncos',
    'Arizona Cardinals $$ Minnesota Vikings',
    'Buffalo Bills $$ Houston Texans',
    'Jacksonville Jaguars $$ Dallas Cowboys',
    'Pittsburgh Steelers $$ Cincinnati Bengals',
    'Carolina Panthers $$ Washington Redskins' ],
  [ 'New York Giants $$ Atlanta Falcons',
    'Dallas Cowboys $$ Washington Redskins',
    'New England Patriots $$ Chicago Bears',
    'Cleveland Browns $$ Tampa Bay Buccaneers',
    'Houston Texans $$ Jacksonville Jaguars',
    'Minnesota Vikings $$ New York Jets',
    'Los Angeles Rams $$ San Francisco 49ers',
    'Buffalo Bills $$ Indianapolis Colts',
    'Tennessee Titans $$ Los Angeles Chargers',
    'Denver Broncos $$ Arizona Cardinals',
    'Detroit Lions $$ Miami Dolphins',
    'Carolina Panthers $$ Philadelphia Eagles',
    'New Orleans Saints $$ Baltimore Ravens',
    'Cincinnati Bengals $$ Kansas City Chiefs' ],
  [ 'Indianapolis Colts $$ Oakland Raiders',
    'Denver Broncos $$ Kansas City Chiefs',
    'Green Bay Packers $$ Los Angeles Rams',
    'Miami Dolphins $$ Houston Texans',
    'New England Patriots $$ Buffalo Bills',
    'Cleveland Browns $$ Pittsburgh Steelers',
    'Tampa Bay Buccaneers $$ Cincinnati Bengals',
    'Philadelphia Eagles $$ Jacksonville Jaguars',
    'San Francisco 49ers $$ Arizona Cardinals',
    'Baltimore Ravens $$ Carolina Panthers',
    'Washington Redskins $$ New York Giants',
    'New Orleans Saints $$ Minnesota Vikings',
    'New York Jets $$ Chicago Bears',
    'Seattle Seahawks $$ Detroit Lions' ],
  [ 'Los Angeles Chargers $$ Seattle Seahawks',
    'Chicago Bears $$ Buffalo Bills',
    'Oakland Raiders $$ San Francisco 49ers',
    'Kansas City Chiefs $$ Cleveland Browns',
    'Tampa Bay Buccaneers $$ Carolina Panthers',
    'Green Bay Packers $$ New England Patriots',
    'New York Jets $$ Miami Dolphins',
    'Los Angeles Rams $$ New Orleans Saints',
    'Atlanta Falcons $$ Washington Redskins',
    'Houston Texans $$ Denver Broncos',
    'Tennessee Titans $$ Dallas Cowboys',
    'Pittsburgh Steelers $$ Baltimore Ravens',
    'Detroit Lions $$ Minnesota Vikings' ],
  [ 'New York Giants $$ San Francisco 49ers',
    'Miami Dolphins $$ Green Bay Packers',
    'Buffalo Bills $$ New York Jets',
    'New England Patriots $$ Tennessee Titans',
    'Los Angeles Chargers $$ Oakland Raiders',
    'New Orleans Saints $$ Cincinnati Bengals',
    'Carolina Panthers $$ Pittsburgh Steelers',
    'Arizona Cardinals $$ Kansas City Chiefs',
    'Washington Redskins $$ Tampa Bay Buccaneers',
    'Detroit Lions $$ Chicago Bears',
    'Atlanta Falcons $$ Cleveland Browns',
    'Seattle Seahawks $$ Los Angeles Rams',
    'Jacksonville Jaguars $$ Indianapolis Colts',
    'Dallas Cowboys $$ Philadelphia Eagles' ],
  [ 'Houston Texans $$ Washington Redskins',
    'Oakland Raiders $$ Arizona Cardinals',
    'Cincinnati Bengals $$ Baltimore Ravens',
    'Minnesota Vikings $$ Chicago Bears',
    'Kansas City Chiefs $$ Los Angeles Rams',
    'Tennessee Titans $$ Indianapolis Colts',
    'Pittsburgh Steelers $$ Jacksonville Jaguars',
    'Carolina Panthers $$ Detroit Lions',
    'Denver Broncos $$ Los Angeles Chargers',
    'Philadelphia Eagles $$ New Orleans Saints',
    'Dallas Cowboys $$ Atlanta Falcons',
    'Green Bay Packers $$ Seattle Seahawks',
    'Tampa Bay Buccaneers $$ New York Giants' ],
  [ 'Oakland Raiders $$ Baltimore Ravens',
    'New England Patriots $$ New York Jets',
    'Tennessee Titans $$ Houston Texans',
    'Arizona Cardinals $$ Los Angeles Chargers',
    'New York Giants $$ Philadelphia Eagles',
    'Chicago Bears $$ Detroit Lions',
    'Miami Dolphins $$ Indianapolis Colts',
    'San Francisco 49ers $$ Tampa Bay Buccaneers',
    'Cleveland Browns $$ Cincinnati Bengals',
    'Pittsburgh Steelers $$ Denver Broncos',
    'Atlanta Falcons $$ New Orleans Saints',
    'Seattle Seahawks $$ Carolina Panthers',
    'Jacksonville Jaguars $$ Buffalo Bills',
    'Washington Redskins $$ Dallas Cowboys',
    'Green Bay Packers $$ Minnesota Vikings' ],
  [ 'Chicago Bears $$ New York Giants',
    'Baltimore Ravens $$ Atlanta Falcons',
    'Kansas City Chiefs $$ Oakland Raiders',
    'Arizona Cardinals $$ Green Bay Packers',
    'Los Angeles Rams $$ Detroit Lions',
    'Denver Broncos $$ Cincinnati Bengals',
    'San Francisco 49ers $$ Seattle Seahawks',
    'New York Jets $$ Tennessee Titans',
    'Los Angeles Chargers $$ Pittsburgh Steelers',
    'New Orleans Saints $$ Dallas Cowboys',
    'Buffalo Bills $$ Miami Dolphins',
    'Cleveland Browns $$ Houston Texans',
    'Indianapolis Colts $$ Jacksonville Jaguars',
    'Washington Redskins $$ Philadelphia Eagles',
    'Carolina Panthers $$ Tampa Bay Buccaneers',
    'Minnesota Vikings $$ New England Patriots' ],
  [ 'Detroit Lions $$ Arizona Cardinals',
    'Carolina Panthers $$ Cleveland Browns',
    'Denver Broncos $$ San Francisco 49ers',
    'New Orleans Saints $$ Tampa Bay Buccaneers',
    'Minnesota Vikings $$ Seattle Seahawks',
    'New York Giants $$ Washington Redskins',
    'Indianapolis Colts $$ Houston Texans',
    'Los Angeles Rams $$ Chicago Bears',
    'Jacksonville Jaguars $$ Tennessee Titans',
    'Baltimore Ravens $$ Kansas City Chiefs',
    'Cincinnati Bengals $$ Los Angeles Chargers',
    'Atlanta Falcons $$ Green Bay Packers',
    'New York Jets $$ Buffalo Bills',
    'New England Patriots $$ Miami Dolphins',
    'Philadelphia Eagles $$ Dallas Cowboys',
    'Pittsburgh Steelers $$ Oakland Raiders' ],
  [ 'Tennessee Titans $$ New York Giants',
    'Cleveland Browns $$ Denver Broncos',
    'New England Patriots $$ Pittsburgh Steelers',
    'Tampa Bay Buccaneers $$ Baltimore Ravens',
    'Green Bay Packers $$ Chicago Bears',
    'Houston Texans $$ New York Jets',
    'New Orleans Saints $$ Carolina Panthers',
    'Detroit Lions $$ Buffalo Bills',
    'Miami Dolphins $$ Minnesota Vikings',
    'Oakland Raiders $$ Cincinnati Bengals',
    'Arizona Cardinals $$ Atlanta Falcons',
    'Los Angeles Chargers $$ Kansas City Chiefs',
    'Philadelphia Eagles $$ Los Angeles Rams',
    'Dallas Cowboys $$ Indianapolis Colts',
    'Washington Redskins $$ Jacksonville Jaguars',
    'Seattle Seahawks $$ San Francisco 49ers' ],
  [ 'Washington Redskins $$ Tennessee Titans',
    'Pittsburgh Steelers $$ New Orleans Saints',
    'Kansas City Chiefs $$ Seattle Seahawks',
    'Minnesota Vikings $$ Detroit Lions',
    'Denver Broncos $$ Oakland Raiders',
    'Atlanta Falcons $$ Carolina Panthers',
    'Baltimore Ravens $$ Los Angeles Chargers',
    'New York Giants $$ Indianapolis Colts',
    'Green Bay Packers $$ New York Jets',
    'Tampa Bay Buccaneers $$ Dallas Cowboys',
    'Los Angeles Rams $$ Arizona Cardinals',
    'Cincinnati Bengals $$ Cleveland Browns',
    'Buffalo Bills $$ New England Patriots',
    'Houston Texans $$ Philadelphia Eagles',
    'Jacksonville Jaguars $$ Miami Dolphins',
    'Chicago Bears $$ San Francisco 49ers' ],
  [ 'Chicago Bears $$ Minnesota Vikings',
    'Cleveland Browns $$ Baltimore Ravens',
    'New York Jets $$ New England Patriots',
    'Indianapolis Colts $$ Tennessee Titans',
    'Arizona Cardinals $$ Seattle Seahawks',
    'Los Angeles Chargers $$ Denver Broncos',
    'Detroit Lions $$ Green Bay Packers',
    'Atlanta Falcons $$ Tampa Bay Buccaneers',
    'San Francisco 49ers $$ Los Angeles Rams',
    'Philadelphia Eagles $$ Washington Redskins',
    'Jacksonville Jaguars $$ Houston Texans',
    'Dallas Cowboys $$ New York Giants',
    'Miami Dolphins $$ Buffalo Bills',
    'Oakland Raiders $$ Kansas City Chiefs',
    'Carolina Panthers $$ New Orleans Saints',
    'Cincinnati Bengals $$ Pittsburgh Steelers' ] ]
